Repository 300CIS017-Object-Oriented-Programming/proyecto-2-snies-extractor-aypoorfis, pull requests merged in 2024-10, with the labels that each got.

#10 6 implementación de clase settings
  src/Settings.cpp
  src/Settings.h
Labels: enhancement

#18 12 creación clase gestorjson
  src/GestorDatos.h
  src/GestorJson.cpp
  src/GestorJson.h
Labels: enhancement

#20 13-creación-de-clase-txt - NEW-MOD: Creacion e implementacion de clas…
  src/GestorDatos.h
  src/GestorJson.cpp
  src/GestorTxt.cpp
  src/GestorTxt.h
Labels: enhancement, syntax reorganization

#24 Issue 19 ( issue1
  README.md
Labels: UML Diagram

#28 26 solucion de error en la clase gestorcsv
  src/GestorCsv.h
Labels: bug

#30 29-solución-de-error-en-la-clase-gestorcsv - FIX: Solución de problem…
  src/GestorCsv.h
Labels: bug

#39 38 cambio de tipo de dato en la funcion convertirstringformaestandar
  src/GestorCsv.cpp
  src/GestorCsv.h
Labels: enhancement

#42 41-reimaginacion-de-metodos-leerarchivo-en-clase-gestorcsv - se imple…
  src/GestorCsv.cpp
  src/GestorCsv.h
Labels: Refactorization

#36 35-actualizacion-en-el-readme-de-nosotros - MOV: se agregaron nuevas …
  README.md
Labels: enhancement

#45 13-actualizacion-en-el-readme - FIX: Eliminacion de funciones en la c…
  README.md
Labels: documentation

#52 49 implementar la función adjuntardatosprogramaacademico de la clase gestorcsv
  src/GestorCsv.cpp
Labels: enhancement, Refactorization

#53 50 implementar la función adjuntardatosarchivo
  src/GestorCsv.cpp
  src/GestorCsv.h
Labels: enhancement, Refactorization

#55 54-refactorizar-sniescontroller-y-de-mas - se acomodaron los gestores…
  src/GestorCsv.h
  src/GestorJson.cpp
  src/GestorJson.h
  src/GestorTxt.cpp
  src/GestorTxt.h
  src/SNIESController.h
Labels: Refactorization

#57 54-refactorizar-sniescontroller-y-de-mas - se acomodaron los gestores…
  src/SNIESController.cpp
  src/SNIESController.h
Labels: Refactorization

#59 54 refactorizar sniescontroller y de mas
  src/GestorCsv.cpp
  src/GestorTxt.cpp
  src/SNIESController.cpp
  src/SNIESController.h
Labels: Refactorization

#63 54-refactorizar-sniescontroller-y-de-mas - Se implemento la funcion c…
  src/SNIESController.cpp
  src/SNIESController.h
  src/Settings.cpp
  src/Settings.h
Labels: Refactorization

#65 54 refactorizar sniescontroller y de mas
  src/ProgramaAcademico.h
  src/SNIESController.cpp
  src/SNIESController.h
Labels: Refactorization

#68 48 refactorización de la clase view y main
  src/View.cpp
  src/View.h
  src/main.cpp
Labels: enhancement

#69 67-nueva-actualizacion-uml - FIX: correcion final del UML
  README.md
Labels: UML Diagram

#70 48-refactorización-de-la-clase-view-y-main - MOV: implementacion calc…
  src/View.cpp
  src/View.h
Labels: enhancement

#71 54-refactorizar-sniescontroller-y-de-mas - Se implemento la funcion o…
  src/SNIESController.cpp
  src/SNIESController.h
Labels: Refactorization

#75 74-ulrimo-arreglo-view - FIX: last bug
  src/View.cpp
Labels: bug
